/**
 * The local mapping file (Feature 31.1): which countries exist in the
 * `globetvapp/epg` XMLTV repository, what their feed files are named, and
 * what suffix their channel ids carry — so nothing downstream ever probes,
 * guesses, or string-derives any of this at runtime.
 *
 * `EPG_COUNTRIES_DATA` (in the sibling `countries-data.ts`, kept separate
 * so this file stays small) is generated by `scripts/generate-epg-countries.mjs`
 * against the live repo — see that script and this module's tail comment
 * for how/when to re-run it.
 *
 * **This file is the half that does not need the table**: the shape, and the
 * three pure functions that take an `EpgCountry` the caller already holds.
 * Every lookup *into* the table lives in `countries-lookup.ts`, which is
 * imported dynamically — the table is 10 KiB nothing needs before first
 * paint, and `catalog.ts`/`xmltv.ts`/`feed-fetch.ts` importing
 * `stripCountrySuffix` or `feedUrls` from here used to drag all of it into
 * the entry chunk.
 */
export interface EpgCountry {
    /** The repo's own folder name, exact casing (`Netherlands`, `Usa`, `Unitedkingdom`). */
    folder: string;
    /** Lowercased file-name prefix (`netherlands`) — `folder.toLowerCase()` for every observed entry, but stored explicitly rather than derived, in case the repo ever diverges. */
    filePrefix: string;
    /** How many `<filePrefix><n>.xml[.gz]` files this folder has, `n` = 1..fileCount, no gaps. */
    fileCount: number;
    /**
     * The channel-id suffix this country's feed actually uses (`nl`, `us`,
     * `uk`) — observed live, never assumed from `iso2` lowercased. Most of
     * the time the two agree; `Unitedkingdom` (`iso2: 'GB'`, `suffix: 'uk'`)
     * is the one folder in this table where they don't, which is exactly
     * why this field exists instead of deriving the suffix on the fly.
     */
    suffix: string;
    /** ISO 3166-1 alpha-2, or `''` for a non-country folder (`kind: 'region'`). */
    iso2: string;
    /** English display name — the folder string is never shown to a user. */
    name: string;
    /** `'region'` for the repo's non-country folders (`Sports`, `Caribbean`, `Scotland`) — excluded from country pickers. */
    kind: 'country' | 'region';
}

const RAW_BASE = 'https://raw.githubusercontent.com/globetvapp/epg/main';

/** The inverse of `countryForLiveToken` — what to write into `settings.liveCountry` for a chosen registry entry. */
export function liveTokenFor(country: EpgCountry): string {
    return country.iso2 || country.suffix.toUpperCase();
}

/** Every `.xml.gz` feed URL for a country, `n` = 1..fileCount — always the gzip variant (~13× smaller than plain, Feature 31.2.2). */
export function feedUrls(country: EpgCountry): string[] {
    return Array.from(
        { length: country.fileCount },
        (_, i) => `${RAW_BASE}/${country.folder}/${country.filePrefix}${String(i + 1)}.xml.gz`,
    );
}

/** The same feed's plain-XML URL — the `DecompressionStream`-unavailable fallback (Feature 31.2.3). */
export function plainFeedUrls(country: EpgCountry): string[] {
    return Array.from(
        { length: country.fileCount },
        (_, i) => `${RAW_BASE}/${country.folder}/${country.filePrefix}${String(i + 1)}.xml`,
    );
}

/**
 * Strips a trailing `.<suffix>` from a feed's own channel id, case-
 * insensitively, only when present — ids can contain other dots
 * (`1-2-3.tv.de` → `1-2-3.tv`), so only the *registered* suffix at the very
 * end is ever removed, never the first or an arbitrary dot.
 */
export function stripCountrySuffix(id: string, country: EpgCountry): string {
    const tail = `.${country.suffix}`;
    return id.toLowerCase().endsWith(tail.toLowerCase()) ? id.slice(0, id.length - tail.length) : id;
}
