import type { EpgCountry } from './countries';

/**
 * GENERATED by `scripts/generate-epg-countries.mjs` — do not hand-edit
 * entries below the marker; re-run the script instead (see its header for
 * how, and `src/epg/README.md` for when).
 *
 * Captured against the live `globetvapp/epg` repo (`main` branch),
 * 2026-07-29: 99 folders — not the ~136 an earlier informal listing
 * estimated; a `git clone --filter=blob:none` (blobless partial clone) of
 * the repo gave an authoritative, zero-guessing folder + file-per-folder
 * count, confirmed against `api.github.com`'s anonymous rate limit being
 * unusable in this environment. `suffix` came from one small ranged fetch
 * per folder (`bytes=0-800` of its first feed file) reading the first
 * `<channel id>` — never assumed from `iso2` lowercased, which is exactly
 * what catches `Unitedkingdom` (`iso2: 'GB'`, real suffix `'uk'`).
 *
 * Hand-verified against the live repo beyond the automated sample —
 * `masterplan/phases/phase-31-epg-country-catalog.md`'s decision notes —
 * for Netherlands, Belgium, Germany, Unitedkingdom, and Usa.
 *
 * `Caribbean`/`Sports`/`Scotland` are `kind: 'region'`: each folder mixes
 * channels from several countries/suffixes under one umbrella (a Caribbean
 * regional bundle, a cross-country sports bundle, Scotland's own feed
 * inside the UK split), so their single `suffix` field is only the *first*
 * sampled channel's suffix, not a fact about every row in that feed —
 * harmless here because `listCountries()` excludes `kind: 'region'` and
 * nothing in Phase 31 selects a region as the active EPG country.
 */
// GENERATED:START
export const EPG_COUNTRIES_DATA: readonly EpgCountry[] = [
    { folder: 'Albania', filePrefix: 'albania', fileCount: 1, suffix: 'al', iso2: 'AL', name: 'Albania', kind: 'country' },
    { folder: 'Argentina', filePrefix: 'argentina', fileCount: 5, suffix: 'ar', iso2: 'AR', name: 'Argentina', kind: 'country' },
    { folder: 'Australia', filePrefix: 'australia', fileCount: 4, suffix: 'au', iso2: 'AU', name: 'Australia', kind: 'country' },
    { folder: 'Austria', filePrefix: 'austria', fileCount: 3, suffix: 'at', iso2: 'AT', name: 'Austria', kind: 'country' },
    { folder: 'Belgium', filePrefix: 'belgium', fileCount: 4, suffix: 'be', iso2: 'BE', name: 'Belgium', kind: 'country' },
    { folder: 'Bolivia', filePrefix: 'bolivia', fileCount: 2, suffix: 'bo', iso2: 'BO', name: 'Bolivia', kind: 'country' },
    { folder: 'Bosnia', filePrefix: 'bosnia', fileCount: 2, suffix: 'ba', iso2: 'BA', name: 'Bosnia and Herzegovina', kind: 'country' },
    { folder: 'Brazil', filePrefix: 'brazil', fileCount: 4, suffix: 'br', iso2: 'BR', name: 'Brazil', kind: 'country' },
    { folder: 'Bulgaria', filePrefix: 'bulgaria', fileCount: 2, suffix: 'bg', iso2: 'BG', name: 'Bulgaria', kind: 'country' },
    { folder: 'Canada', filePrefix: 'canada', fileCount: 3, suffix: 'ca', iso2: 'CA', name: 'Canada', kind: 'country' },
    { folder: 'Caribbean', filePrefix: 'caribbean', fileCount: 1, suffix: 'tt', iso2: '', name: 'Caribbean', kind: 'region' },
    { folder: 'Chile', filePrefix: 'chile', fileCount: 2, suffix: 'cl', iso2: 'CL', name: 'Chile', kind: 'country' },
    { folder: 'China', filePrefix: 'china', fileCount: 2, suffix: 'cn', iso2: 'CN', name: 'China', kind: 'country' },
    { folder: 'Colombia', filePrefix: 'colombia', fileCount: 2, suffix: 'co', iso2: 'CO', name: 'Colombia', kind: 'country' },
    { folder: 'Costarica', filePrefix: 'costarica', fileCount: 1, suffix: 'cr', iso2: 'CR', name: 'Costa Rica', kind: 'country' },
    { folder: 'Croatia', filePrefix: 'croatia', fileCount: 5, suffix: 'hr', iso2: 'HR', name: 'Croatia', kind: 'country' },
    { folder: 'Cyprus', filePrefix: 'cyprus', fileCount: 1, suffix: 'cy', iso2: 'CY', name: 'Cyprus', kind: 'country' },
    { folder: 'Czech', filePrefix: 'czech', fileCount: 2, suffix: 'cz', iso2: 'CZ', name: 'Czech Republic', kind: 'country' },
    { folder: 'Denmark', filePrefix: 'denmark', fileCount: 6, suffix: 'dk', iso2: 'DK', name: 'Denmark', kind: 'country' },
    { folder: 'Dominican', filePrefix: 'dominican', fileCount: 1, suffix: 'do', iso2: 'DO', name: 'Dominican Republic', kind: 'country' },
    { folder: 'Ecuador', filePrefix: 'ecuador', fileCount: 1, suffix: 'ec', iso2: 'EC', name: 'Ecuador', kind: 'country' },
    { folder: 'Egypt', filePrefix: 'egypt', fileCount: 2, suffix: 'eg', iso2: 'EG', name: 'Egypt', kind: 'country' },
    { folder: 'Elsalvador', filePrefix: 'elsalvador', fileCount: 1, suffix: 'sv', iso2: 'SV', name: 'El Salvador', kind: 'country' },
    { folder: 'Estonia', filePrefix: 'estonia', fileCount: 1, suffix: 'ee', iso2: 'EE', name: 'Estonia', kind: 'country' },
    { folder: 'Finland', filePrefix: 'finland', fileCount: 4, suffix: 'fi', iso2: 'FI', name: 'Finland', kind: 'country' },
    { folder: 'France', filePrefix: 'france', fileCount: 2, suffix: 'fr', iso2: 'FR', name: 'France', kind: 'country' },
    { folder: 'Georgia', filePrefix: 'georgia', fileCount: 2, suffix: 'ge', iso2: 'GE', name: 'Georgia', kind: 'country' },
    { folder: 'Germany', filePrefix: 'germany', fileCount: 4, suffix: 'de', iso2: 'DE', name: 'Germany', kind: 'country' },
    { folder: 'Ghana', filePrefix: 'ghana', fileCount: 1, suffix: 'gh', iso2: 'GH', name: 'Ghana', kind: 'country' },
    { folder: 'Greece', filePrefix: 'greece', fileCount: 3, suffix: 'gr', iso2: 'GR', name: 'Greece', kind: 'country' },
    { folder: 'Guatemala', filePrefix: 'guatemala', fileCount: 1, suffix: 'gt', iso2: 'GT', name: 'Guatemala', kind: 'country' },
    { folder: 'Honduras', filePrefix: 'honduras', fileCount: 1, suffix: 'hn', iso2: 'HN', name: 'Honduras', kind: 'country' },
    { folder: 'Hongkong', filePrefix: 'hongkong', fileCount: 3, suffix: 'hk', iso2: 'HK', name: 'Hong Kong', kind: 'country' },
    { folder: 'Hungary', filePrefix: 'hungary', fileCount: 1, suffix: 'hu', iso2: 'HU', name: 'Hungary', kind: 'country' },
    { folder: 'Iceland', filePrefix: 'iceland', fileCount: 3, suffix: 'is', iso2: 'IS', name: 'Iceland', kind: 'country' },
    { folder: 'India', filePrefix: 'india', fileCount: 5, suffix: 'in', iso2: 'IN', name: 'India', kind: 'country' },
    { folder: 'Indonesia', filePrefix: 'indonesia', fileCount: 6, suffix: 'id', iso2: 'ID', name: 'Indonesia', kind: 'country' },
    { folder: 'Ireland', filePrefix: 'ireland', fileCount: 1, suffix: 'ie', iso2: 'IE', name: 'Ireland', kind: 'country' },
    { folder: 'Israel', filePrefix: 'israel', fileCount: 2, suffix: 'il', iso2: 'IL', name: 'Israel', kind: 'country' },
    { folder: 'Italy', filePrefix: 'italy', fileCount: 5, suffix: 'it', iso2: 'IT', name: 'Italy', kind: 'country' },
    { folder: 'Ivorycoast', filePrefix: 'ivorycoast', fileCount: 1, suffix: 'ci', iso2: 'CI', name: 'Ivory Coast', kind: 'country' },
    { folder: 'Jamaica', filePrefix: 'jamaica', fileCount: 1, suffix: 'jm', iso2: 'JM', name: 'Jamaica', kind: 'country' },
    { folder: 'Kenya', filePrefix: 'kenya', fileCount: 1, suffix: 'ke', iso2: 'KE', name: 'Kenya', kind: 'country' },
    { folder: 'Korea', filePrefix: 'korea', fileCount: 1, suffix: 'kr', iso2: 'KR', name: 'South Korea', kind: 'country' },
    { folder: 'Latvia', filePrefix: 'latvia', fileCount: 2, suffix: 'lv', iso2: 'LV', name: 'Latvia', kind: 'country' },
    { folder: 'Lithuania', filePrefix: 'lithuania', fileCount: 3, suffix: 'lt', iso2: 'LT', name: 'Lithuania', kind: 'country' },
    { folder: 'Luxembourg', filePrefix: 'luxembourg', fileCount: 1, suffix: 'lu', iso2: 'LU', name: 'Luxembourg', kind: 'country' },
    { folder: 'Macau', filePrefix: 'macau', fileCount: 1, suffix: 'mo', iso2: 'MO', name: 'Macau', kind: 'country' },
    { folder: 'Madagascar', filePrefix: 'madagascar', fileCount: 1, suffix: 'mg', iso2: 'MG', name: 'Madagascar', kind: 'country' },
    { folder: 'Malawi', filePrefix: 'malawi', fileCount: 1, suffix: 'mw', iso2: 'MW', name: 'Malawi', kind: 'country' },
    { folder: 'Malaysia', filePrefix: 'malaysia', fileCount: 3, suffix: 'my', iso2: 'MY', name: 'Malaysia', kind: 'country' },
    { folder: 'Malta', filePrefix: 'malta', fileCount: 1, suffix: 'mt', iso2: 'MT', name: 'Malta', kind: 'country' },
    { folder: 'Mauritius', filePrefix: 'mauritius', fileCount: 1, suffix: 'mu', iso2: 'MU', name: 'Mauritius', kind: 'country' },
    { folder: 'Mexico', filePrefix: 'mexico', fileCount: 2, suffix: 'mx', iso2: 'MX', name: 'Mexico', kind: 'country' },
    { folder: 'Mongolia', filePrefix: 'mongolia', fileCount: 1, suffix: 'mn', iso2: 'MN', name: 'Mongolia', kind: 'country' },
    { folder: 'Montenegro', filePrefix: 'montenegro', fileCount: 1, suffix: 'me', iso2: 'ME', name: 'Montenegro', kind: 'country' },
    { folder: 'Morocco', filePrefix: 'morocco', fileCount: 2, suffix: 'ma', iso2: 'MA', name: 'Morocco', kind: 'country' },
    { folder: 'Mozambique', filePrefix: 'mozambique', fileCount: 1, suffix: 'mz', iso2: 'MZ', name: 'Mozambique', kind: 'country' },
    { folder: 'Namibia', filePrefix: 'namibia', fileCount: 1, suffix: 'na', iso2: 'NA', name: 'Namibia', kind: 'country' },
    { folder: 'Netherlands', filePrefix: 'netherlands', fileCount: 2, suffix: 'nl', iso2: 'NL', name: 'Netherlands', kind: 'country' },
    { folder: 'Newcaledonia', filePrefix: 'newcaledonia', fileCount: 1, suffix: 'nc', iso2: 'NC', name: 'New Caledonia', kind: 'country' },
    { folder: 'Newzealand', filePrefix: 'newzealand', fileCount: 1, suffix: 'nz', iso2: 'NZ', name: 'New Zealand', kind: 'country' },
    { folder: 'Nigeria', filePrefix: 'nigeria', fileCount: 1, suffix: 'ng', iso2: 'NG', name: 'Nigeria', kind: 'country' },
    { folder: 'Norway', filePrefix: 'norway', fileCount: 2, suffix: 'no', iso2: 'NO', name: 'Norway', kind: 'country' },
    { folder: 'Pakistan', filePrefix: 'pakistan', fileCount: 2, suffix: 'pk', iso2: 'PK', name: 'Pakistan', kind: 'country' },
    { folder: 'Panama', filePrefix: 'panama', fileCount: 1, suffix: 'pa', iso2: 'PA', name: 'Panama', kind: 'country' },
    { folder: 'Paraguay', filePrefix: 'paraguay', fileCount: 2, suffix: 'py', iso2: 'PY', name: 'Paraguay', kind: 'country' },
    { folder: 'Peru', filePrefix: 'peru', fileCount: 2, suffix: 'pe', iso2: 'PE', name: 'Peru', kind: 'country' },
    { folder: 'Philippines', filePrefix: 'philippines', fileCount: 3, suffix: 'ph', iso2: 'PH', name: 'Philippines', kind: 'country' },
    { folder: 'Poland', filePrefix: 'poland', fileCount: 2, suffix: 'pl', iso2: 'PL', name: 'Poland', kind: 'country' },
    { folder: 'Portugal', filePrefix: 'portugal', fileCount: 2, suffix: 'pt', iso2: 'PT', name: 'Portugal', kind: 'country' },
    { folder: 'Puertorico', filePrefix: 'puertorico', fileCount: 2, suffix: 'pr', iso2: 'PR', name: 'Puerto Rico', kind: 'country' },
    { folder: 'Qatar', filePrefix: 'qatar', fileCount: 6, suffix: 'qa', iso2: 'QA', name: 'Qatar', kind: 'country' },
    { folder: 'Romania', filePrefix: 'romania', fileCount: 2, suffix: 'ro', iso2: 'RO', name: 'Romania', kind: 'country' },
    { folder: 'Russia', filePrefix: 'russia', fileCount: 3, suffix: 'ru', iso2: 'RU', name: 'Russia', kind: 'country' },
    { folder: 'Saudiarabia', filePrefix: 'saudiarabia', fileCount: 4, suffix: 'sa', iso2: 'SA', name: 'Saudi Arabia', kind: 'country' },
    { folder: 'Scotland', filePrefix: 'scotland', fileCount: 1, suffix: 'sco', iso2: '', name: 'Scotland', kind: 'region' },
    { folder: 'Serbia', filePrefix: 'serbia', fileCount: 3, suffix: 'rs', iso2: 'RS', name: 'Serbia', kind: 'country' },
    { folder: 'Singapore', filePrefix: 'singapore', fileCount: 3, suffix: 'sg', iso2: 'SG', name: 'Singapore', kind: 'country' },
    { folder: 'Slovakia', filePrefix: 'slovakia', fileCount: 3, suffix: 'sk', iso2: 'SK', name: 'Slovakia', kind: 'country' },
    { folder: 'Slovenia', filePrefix: 'slovenia', fileCount: 3, suffix: 'si', iso2: 'SI', name: 'Slovenia', kind: 'country' },
    { folder: 'Southafrica', filePrefix: 'southafrica', fileCount: 2, suffix: 'za', iso2: 'ZA', name: 'South Africa', kind: 'country' },
    { folder: 'Spain', filePrefix: 'spain', fileCount: 5, suffix: 'es', iso2: 'ES', name: 'Spain', kind: 'country' },
    { folder: 'Sports', filePrefix: 'sports', fileCount: 3, suffix: 'qa', iso2: '', name: 'Sports', kind: 'region' },
    { folder: 'Sweden', filePrefix: 'sweden', fileCount: 4, suffix: 'se', iso2: 'SE', name: 'Sweden', kind: 'country' },
    { folder: 'Switzerland', filePrefix: 'switzerland', fileCount: 3, suffix: 'ch', iso2: 'CH', name: 'Switzerland', kind: 'country' },
    { folder: 'Taiwan', filePrefix: 'taiwan', fileCount: 2, suffix: 'tw', iso2: 'TW', name: 'Taiwan', kind: 'country' },
    { folder: 'Thailand', filePrefix: 'thailand', fileCount: 2, suffix: 'th', iso2: 'TH', name: 'Thailand', kind: 'country' },
    { folder: 'Turkey', filePrefix: 'turkey', fileCount: 5, suffix: 'tr', iso2: 'TR', name: 'Turkey', kind: 'country' },
    { folder: 'Uae', filePrefix: 'uae', fileCount: 2, suffix: 'ae', iso2: 'AE', name: 'United Arab Emirates', kind: 'country' },
    { folder: 'Uganda', filePrefix: 'uganda', fileCount: 1, suffix: 'ug', iso2: 'UG', name: 'Uganda', kind: 'country' },
    { folder: 'Ukraine', filePrefix: 'ukraine', fileCount: 1, suffix: 'ua', iso2: 'UA', name: 'Ukraine', kind: 'country' },
    { folder: 'Unitedkingdom', filePrefix: 'unitedkingdom', fileCount: 5, suffix: 'uk', iso2: 'GB', name: 'United Kingdom', kind: 'country' },
    { folder: 'Uruguay', filePrefix: 'uruguay', fileCount: 2, suffix: 'uy', iso2: 'UY', name: 'Uruguay', kind: 'country' },
    { folder: 'Usa', filePrefix: 'usa', fileCount: 6, suffix: 'us', iso2: 'US', name: 'United States', kind: 'country' },
    { folder: 'Uzbekistan', filePrefix: 'uzbekistan', fileCount: 1, suffix: 'uz', iso2: 'UZ', name: 'Uzbekistan', kind: 'country' },
    { folder: 'Venezuela', filePrefix: 'venezuela', fileCount: 1, suffix: 've', iso2: 'VE', name: 'Venezuela', kind: 'country' },
    { folder: 'Vietnam', filePrefix: 'vietnam', fileCount: 1, suffix: 'vn', iso2: 'VN', name: 'Vietnam', kind: 'country' },
    { folder: 'Zambia', filePrefix: 'zambia', fileCount: 1, suffix: 'zm', iso2: 'ZM', name: 'Zambia', kind: 'country' },
];
// GENERATED:END
