/** German counterpart of `strings.en.catalog.ts` — see its header for why this is a separate file. */
export const deCatalog = {
    catalog: {
        loading: 'Wird geladen…',
        itemsLabel: 'Titel',
        noSource: 'Verbinden Sie ein Xtream-Codes-Konto, um diesen Katalog zu durchsuchen.',
        noSourceAction: 'Einstellungen öffnen',
        fetchFailed: 'Dieser Katalog konnte nicht geladen werden. Versuchen Sie es gleich noch einmal.',
        noCategories: 'Dieser Anbieter hat keine Kategorien zum Anzeigen.',
        emptyCategory: 'Noch nichts in dieser Kategorie.',
        close: 'Schließen',
        play: 'Abspielen',
        retry: 'Erneut versuchen',
        offline: 'Gespeicherte Daten — der Anbieter war nicht erreichbar. Heruntergeladene Titel laufen weiterhin.',
        variantsToggle: 'Andere Versionen dieser Kategorie',
        noSoundWarning: 'Kein Ton auf diesem Gerät — für die Tonspur dieses Titels (Dolby oder DTS) gibt es hier keinen Decoder.',
        noPictureWarning: 'Kein Decoder für das Video dieses Titels auf diesem Gerät; er läuft möglicherweise nicht.',
    },

    movies: {
        categoriesAria: 'Filmkategorien',
        detailAria: 'Filmdetails',
    },

    series: {
        categoriesAria: 'Serienkategorien',
        detailAria: 'Seriendetails',
        seasonPrefix: 'Staffel',
        episodePrefix: 'F',
        minutesSuffix: 'Min.',
        noEpisodes: 'Für diese Serie sind noch keine Folgen gelistet.',
        nextUpLabel: 'Als Nächstes',
        nextPlay: 'Nächste abspielen',
        nextDismiss: 'Schließen',
        nextAria: 'Nächste Folge',
    },

    downloads: {
        action: 'Herunterladen',
        queueTitle: 'Downloads',
        queueAria: 'Download-Warteschlange',
        progressAria: 'Download-Fortschritt',
        cancel: 'Abbrechen',
        remove: 'Entfernen',
        clearFinished: 'Abgeschlossene entfernen',
        queued: 'Wartet…',
        starting: 'Startet…',
        done: 'Gespeichert',
        cancelled: 'Abgebrochen',
        handoff: 'An die Downloads deines Browsers übergeben.',
        errorNetwork:
            'Die Übertragung wurde gestoppt. Anbieter begrenzen meist, wie viele Verbindungen ein Konto gleichzeitig öffnen darf — erst die Wiedergabe zu stoppen hilft oft.',
        errorDisk: 'Die Datei konnte nicht geschrieben werden. Prüfe, ob das Ziel noch existiert und genug Platz hat.',
    },

    search: {
        placeholder: 'Titel suchen…',
        clear: 'Suche löschen',
        scopeAll: 'Alle',
        scopeChannels: 'Sender',
        scopeMovies: 'Filme',
        scopeSeries: 'Serien',
        loadedOnlyHint: 'Durchsucht nur bereits geladene Titel — öffnen Sie weitere Kategorien für vollständigere Ergebnisse.',
        allOff: 'Alle Anbieter durchsuchen',
        allOn: 'Durchsucht alle Anbieter — zurück zu diesem',
        partialHint: 'Einige Anbieter waren nicht erreichbar, diese Ergebnisse sind daher unvollständig.',
        sweepTitle: 'Alle Anbieter durchsuchen',
        sweepWarning:
            'Damit wird der komplette Film- und Serienkatalog jedes eingerichteten Anbieters geladen. Das kann mehrere Minuten dauern und überträgt viele Daten. Das Ergebnis wird einen Tag lang gespeichert, die nächste Suche ist also sofort da.',
        sweepStart: 'Starten',
        sweepProviders: 'Anbieter',
        sweepCategories: 'Kategorien',
        sweepItems: 'Gefundene Titel',
        sweepFailed: 'Nicht erreichbar',
        sweepPartial: 'Fertig, aber unvollständig — einige Anbieter wurden übersprungen oder schlugen fehl.',
        sweepComplete: 'Fertig — alle Anbieter wurden erfasst.',
        sweepCancelled: 'Gestoppt. Alles bereits Geladene bleibt erhalten.',
    },
    /** Der Listen-/Raster-Umschalter neben dem Suchfeld jeder Ansicht. */
    layout: {
        group: 'Ansicht',
        list: 'Listenansicht',
        grid: 'Rasteransicht',
    },
} as const;
