#!/usr/bin/env node
/**
 * ThunderTV's strict-CSP bridge for Spektrum 1.1.
 *
 * Spektrum's published compiler emits `with (state)` inside an ES module.
 * ES modules are always strict mode, where `with` is a syntax error. This
 * generator keeps the same runtime semantics but emits a normal, external
 * classic script. The functions are parsed as source by the browser (which
 * CSP permits); there is no eval/new Function at runtime.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const repoRoot = fileURLToPath(new URL('..', import.meta.url));
export const generatedPath = `${repoRoot}public/vendor/spektrum-precompiled.js`;

const MUSTACHE = /\{\{\s*([^}]+?)\s*\}\}/g;
const ATTR_BIND = /(?:\s|^)(:[\w-]+|data-if|data-key)\s*=\s*(["'])(.*?)\2/gs;

/** Keep this scanner in lockstep with the four expression forms Spektrum binds. */
export function extractExpressions(html) {
    // Spektrum walks DOM text nodes and attributes, not HTML comments.
    const template = html.replace(/<!--[\s\S]*?-->/g, '');
    const seen = new Set();
    for (const match of template.matchAll(MUSTACHE)) {
        const value = match[1].trim();
        if (value) seen.add(value);
    }
    for (const match of template.matchAll(ATTR_BIND)) {
        const value = match[3].trim();
        if (value) seen.add(value);
    }
    return [...seen];
}

function normalizeNumericPaths(source) {
    return source.replace(
        /([a-zA-Z_$][\w$]*)((?:\.\d+)+)/g,
        (_match, head, tail) => head + tail.replace(/\.(\d+)/g, '[$1]'),
    );
}

export function emitClassicPrecompileSource(expressions) {
    const records = expressions.map((source) => {
        const normalized = normalizeNumericPaths(source);
        return (
            `[${JSON.stringify(source)},function(state,scope){try{` +
            `with(state)with(scope||{})return(${normalized})` +
            `}catch{return void 0}}]`
        );
    });

    return [
        '/* Generated by scripts/spektrum-csp.mjs. Do not edit. */',
        '(function(g){',
        `const records=[${records.join(',')}];`,
        "Object.defineProperty(g,'__THUNDERTV_CSP_EXPRESSIONS__',{value:records,configurable:true});",
        '})(globalThis);',
        '',
    ].join('\n');
}

export function expectedGeneratedSource() {
    const html = readFileSync(`${repoRoot}index.html`, 'utf8');
    return emitClassicPrecompileSource(extractExpressions(html));
}

function main() {
    const expected = expectedGeneratedSource();
    let actual = '';
    try {
        actual = readFileSync(generatedPath, 'utf8');
    } catch {
        // Missing output is handled by check/write below.
    }
    if (process.argv.includes('--check')) {
        if (actual !== expected) {
            console.error('spektrum-csp: generated expression registry is missing or stale; run "npm run spektrum:csp"');
            process.exit(1);
        }
        console.log(`spektrum-csp: OK — ${String(extractExpressions(readFileSync(`${repoRoot}index.html`, 'utf8')).length)} expressions precompiled`);
        return;
    }
    if (actual === expected) {
        console.log(`spektrum-csp: current — ${generatedPath}`);
        return;
    }
    writeFileSync(generatedPath, expected);
    console.log(`spektrum-csp: wrote ${generatedPath}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
